### ISSUE TITLE
Few Ask Hints cannot be solved

### ISSUE THREAD

**Issue by Potatosynthesis** [silverhawke249/silver-meadow#1]
Technically not the issue of the pack itself, but the game and the editor have gone through so many updates that Few Ask Hints no longer works properly. Letters refuse to function because the corresponding words (e.g. IS) are not in the object palette.

This problem seems more severe in your other pack (Nonlinearity).

**Comment by silverhawke249** [comment]
a447975 should fix this issue. please download the latest release and tell me how that pans out.

**Comment by Potatosynthesis** [comment]
Letter levels are working now. Thanks.
